### ISSUE TITLE
História 2 do Épico 1

### ISSUE THREAD

**Issue by berarchegas** [MC426/Projeto#18]
| História 02 | Alteração de consulta médica |
| ----- | ------------------------------- |
| Como  | Paciente                        |
| Eu gostaria de | Poder remarcar uma nova consulta médica |
| De forma que | Não fosse preciso ligar ao consultório durante horário comercial |

**Comment by brenofranca83** [comment]
Se é remarcar, não é uma **nova** consulta.

**Comment by NaimSS** [comment]
Fechar para abrir outra issue com a história correta
