### ISSUE TITLE
História 2 do Épico 3

### ISSUE THREAD

**Issue by luizoda** [MC426/Projeto#26]
| História 2 derivada do Épico 3         |   Disponibilizar agenda da sala de cirurgia                  |      
| ------------------------------------- | ------- | 
| Como                                  | Clínica  |  
| Eu gostaria de                       | liberar e alterar minha agenda de disponibilidade da sala de cirurgia | 
| De forma que                         | os médicos não tenham que entrar em contato direto com a clínica |

**Comment by brenofranca83** [comment]
Tem duas histórias em uma

**Comment by NaimSS** [comment]
Fechar aqui e criar outra com so uma das historias
